version: '3.7'

services:
  forex-rates:
    image: uday07/miv2-forex-rates-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - forex-network
    depends_on:
      - naming-server
      - zipkin-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans

  forex-converter:
    image: uday07/miv2-forex-converter-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - forex-network
    depends_on:
      - naming-server
      - zipkin-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans

  api-gateway:
    image: uday07/miv2-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - forex-network
    depends_on:
      - naming-server
      - zipkin-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans

  naming-server:
    image: uday07/miv2-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - forex-network

  zipkin-server:
    image: openzipkin/zipkin:3
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - forex-network
    restart: always

networks:
  forex-network: