spring:
  application:
    name: forex-converter-service
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    sleuth:
      tracing:
        enabled: true

server:
  port: 8000
  error:
    include-stacktrace: never

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  retry:
    instances:
      convert:
        maxAttempts: 5
        waitDuration: 1s
        enableExponentialBackoff: true
  rateLimiter:
    instances:
      default:
        limitForPeriod: 10
        limitRefreshPeriod: 10s
  bulkhead:
    instances:
      default:
        maxConcurrentCalls: 10
        maxQueueSize: 10

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

feign:
  trace:
    enabled: true