spring:
  application:
    name: forex-converter-service

server:
  port: 8000
  error:
    include-stacktrace: never

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  retry:
    instances:
      converted-amount:
        maxAttempts: 5
        waitDuration: 1s